plugins {
	id 'java'
}

version = project.properties['mod_version']
base.archivesName = project.properties['archives_base_name']

java {
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
	mavenCentral()
	flatDir {
		dirs 'libs'
	}
}

dependencies {
	compileOnly name: 'minecraft-b1.7.3'
	compileOnly name: 'modloader-b1.7.3'
}

sourceSets {
	main {
		java {
			srcDirs = ['src/main/java']
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
}

jar {
	archiveClassifier.set('')
	from(sourceSets.main.output)
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}